workflows:
  ios-signed-build:
    name: iOS Build - With Code Signing
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # הגדרות חתימה - צריך להגדיר בממשק הניהול של Codemagic
      ios_signing:
        distribution_type: app_store  # או ad_hoc לטסטים
        bundle_identifier: com.nituvim.ios  # Bundle ID לפרויקט ניתובים
      
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
    
    scripts:
      - name: Check and create iOS directory
        script: |
          echo "Checking if iOS directory exists..."
          if [ ! -d "ios" ]; then
            echo "iOS directory not found. Creating iOS platform..."
            flutter create . --platforms=ios
          else
            echo "iOS directory already exists."
          fi
          
      - name: Get Flutter dependencies
        script: |
          echo "Getting Flutter dependencies..."
          flutter packages pub get
          
      - name: Install CocoaPods dependencies
        script: |
          echo "Installing CocoaPods dependencies..."
          cd ios && pod install --repo-update
          
      - name: Flutter clean and prepare
        script: |
          echo "Cleaning Flutter project..."
          flutter clean
          flutter packages pub get
          
      - name: Build iOS with signing
        script: |
          echo "Building iOS with code signing for distribution..."
          flutter build ios --release
          
      - name: Build IPA
        script: |
          echo "Creating IPA file..."
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-flags "-destination 'generic/platform=iOS'"
          
      - name: List build artifacts
        script: |
          echo "Listing build artifacts..."
          find build -name "*.app" -type d
          find build -name "*.ipa" -type f
          find build -name "*.dSYM" -type d
          ls -la build/ios/
          
    artifacts:
      # קובץ IPA חתום
      - build/ios/ipa/*.ipa
      
      # תיקיית iOS המלאה
      - ios/**
      
      # תוצרי Build
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.dSYM
      
      # לוגים
      - flutter_drive.log
      - build.log
      
    publishing:
      # העלאה לApp Store Connect (אופציונלי)
      app_store_connect:
        # api_key: $APP_STORE_CONNECT_PRIVATE_KEY  # צריך להגדיר בממשק
        # key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER  # צריך להגדיר בממשק
        # issuer_id: $APP_STORE_CONNECT_ISSUER_ID   # צריך להגדיר בממשק
        
        submit_to_testflight: false  # משנה ל-true אם רוצה להעלות ל-TestFlight
        submit_to_app_store: false   # משנה ל-true אם רוצה להעלות ל-App Store
        
      email:
        recipients:
          - Idanmagor325@gmail.com
        notify:
          success: true
          failure: true

  ios-build-workflow:
    name: iOS Build - No Signing
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
    
    scripts:
      - name: Check and create iOS directory
        script: |
          echo "Checking if iOS directory exists..."
          if [ ! -d "ios" ]; then
            echo "iOS directory not found. Creating iOS platform..."
            flutter create . --platforms=ios
          else
            echo "iOS directory already exists."
          fi
          
      - name: Get Flutter dependencies
        script: |
          echo "Getting Flutter dependencies..."
          flutter packages pub get
          
      - name: Install CocoaPods dependencies
        script: |
          echo "Installing CocoaPods dependencies..."
          cd ios && pod install --repo-update
          
      - name: Flutter clean and prepare
        script: |
          echo "Cleaning Flutter project..."
          flutter clean
          flutter packages pub get
          
      - name: Build iOS without signing
        script: |
          echo "Building iOS without code signing..."
          flutter build ios --debug --no-codesign
          
      - name: List build artifacts
        script: |
          echo "Listing build artifacts..."
          find build -name "*.app" -type d
          find build -name "*.dSYM" -type d
          ls -la ios/
          
    artifacts:
      # תיקיית iOS המלאה
      - ios/**
      
      # תוצרי Build
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.dSYM
      - build/ios/iphonesimulator/*.app
      - build/ios/iphonesimulator/*.dSYM
      
      # קבצי build נוספים
      - build/ios/Debug-iphoneos/
      - build/ios/Debug-iphonesimulator/
      
      # לוגים
      - flutter_drive.log
      - build.log
      
    publishing:
      email:
        recipients:
          - Idanmagor325@gmail.com
        notify:
          success: true
          failure: true

  # Workflow מהיר לבדיקות
  ios-quick-build:
    name: iOS Quick Build - Simulator Only
    instance_type: mac_mini_m1
    max_build_duration: 30
    
    environment:
      flutter: stable
      xcode: latest
      
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.pub-cache
        
    scripts:
      - name: Check and create iOS directory
        script: |
          if [ ! -d "ios" ]; then
            flutter create . --platforms=ios
          fi
          
      - name: Get dependencies
        script: |
          flutter packages pub get
        
      - name: Build for simulator only
        script: |
          flutter build ios --debug --no-codesign --simulator
        
    artifacts:
      - ios/**
      - build/ios/iphonesimulator/*.app
      
    publishing:
      email:
        recipients:
          - Idanmagor325@gmail.com
        notify:
          success: true
          failure: true

  # Debug workflow for faster testing
  ios-debug:
    name: iOS Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    
    environment:
      flutter: stable
      xcode: latest
      
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
        
      - name: Build debug
        script: flutter build ios --debug --no-codesign --simulator
        
    artifacts:
      - build/ios/iphonesimulator/*.app
      
    publishing:
      email:
        recipients:
          - Idanmagor325@gmail.com
        notify:
          success: true
          failure: true 