workflows:
  ios-signed-build:
    name: iOS Build - No Code Signing
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
    
    scripts:
      - name: Check and create iOS directory
        script: |
          echo "Checking iOS platform setup..."
          if [ ! -f "ios/Podfile" ] || [ ! -d "ios/Runner.xcodeproj" ]; then
            echo "iOS platform incomplete. Recreating iOS platform..."
            rm -rf ios
            flutter create . --platforms=ios
            echo "iOS platform created successfully!"
          else
            echo "iOS platform already properly configured."
          fi
          
          # Verify iOS platform is properly set up
          ls -la ios/
          if [ -f "ios/Podfile" ]; then
            echo "✅ Podfile found"
          else
            echo "❌ Podfile missing - this will cause CocoaPods to fail"
            exit 1
          fi
          
      - name: Get Flutter dependencies
        script: |
          echo "Getting Flutter dependencies..."
          flutter packages pub get
          
      - name: Fix iOS deployment target and bundle ID
        script: |
          echo "Fixing iOS deployment target to match Podfile..."
          # Update Xcode project deployment target to 13.0
          sed -i 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' ios/Runner.xcodeproj/project.pbxproj
          
          # Update bundle identifier to be more specific
          sed -i 's/com.example.nituvimIos/com.nituvim.app/g' ios/Runner.xcodeproj/project.pbxproj
          
          echo "iOS deployment target updated to 13.0"
          echo "Bundle identifier updated to com.nituvim.app"
          
          # Verify the changes
          echo "Verifying deployment target fix:"
          grep "IPHONEOS_DEPLOYMENT_TARGET" ios/Runner.xcodeproj/project.pbxproj | head -3
          echo "Verifying bundle ID fix:"
          grep "PRODUCT_BUNDLE_IDENTIFIER" ios/Runner.xcodeproj/project.pbxproj | head -3
          
      - name: Install CocoaPods dependencies
        script: |
          echo "Installing CocoaPods dependencies..."
          if [ ! -f "ios/Podfile" ]; then
            echo "❌ Podfile not found! Cannot install CocoaPods dependencies."
            exit 1
          fi
          cd ios
          echo "Contents of ios directory:"
          ls -la
          echo "CocoaPods version:"
          pod --version
          echo "Running pod install with verbose output..."
          pod install --repo-update --verbose
          
      - name: Flutter clean and prepare
        script: |
          echo "Cleaning Flutter project..."
          flutter clean
          flutter packages pub get
          
      - name: Build iOS without signing
        script: |
          echo "Building iOS without code signing..."
          
          # Verify iOS project structure
          echo "Checking iOS project structure:"
          ls -la ios/
          if [ ! -d "ios/Runner.xcodeproj" ]; then
            echo "❌ Runner.xcodeproj not found!"
            exit 1
          fi
          if [ ! -f "ios/Runner.xcworkspace/contents.xcworkspacedata" ]; then
            echo "❌ Runner.xcworkspace not found! CocoaPods might have failed."
            exit 1
          fi
          
          # Show Flutter and Xcode versions
          echo "Flutter version:"
          flutter --version
          echo "Xcode version:"
          xcodebuild -version
          
          # Clean build directory
          echo "Cleaning build directory..."
          rm -rf build/ios
          
          # Check if main.dart exists
          if [ ! -f "lib/main.dart" ]; then
            echo "❌ lib/main.dart not found!"
            exit 1
          fi
          
          # Try building for simulator first (easier)
          echo "Building iOS app for simulator..."
          flutter build ios \
            --debug \
            --no-codesign \
            --simulator \
            --target lib/main.dart \
            --verbose
          
          # Also try building for device
          echo "Building iOS app for device..."
          flutter build ios \
            --debug \
            --no-codesign \
            --target lib/main.dart \
            --verbose
          
          # Verify build output
          echo "Build completed. Checking all outputs:"
          find build -name "*.app" -type d | head -10
          echo "Checking build directory structure:"
          ls -la build/
          if [ -d "build/ios" ]; then
            echo "iOS build directory contents:"
            ls -la build/ios/
          fi
          
      - name: Copy built apps to artifacts location
        script: |
          echo "Ensuring build artifacts are properly organized..."
          mkdir -p build/ios/artifacts
          
          # Copy any .app files found
          find build -name "*.app" -type d -exec cp -r {} build/ios/artifacts/ \;
          
          echo "Final artifacts check:"
          ls -la build/ios/artifacts/ || echo "No artifacts directory created"
          
      # - name: Build IPA (disabled - requires code signing)
      #   script: |
      #     echo "Creating IPA file..."
      #     xcode-project build-ipa \
      #       --workspace ios/Runner.xcworkspace \
      #       --scheme Runner \
      #       --archive-flags "-destination 'generic/platform=iOS'"
          
      - name: List build artifacts
        script: |
          echo "Listing build artifacts..."
          find build -name "*.app" -type d
          find build -name "*.ipa" -type f
          find build -name "*.dSYM" -type d
          ls -la build/ios/
          
    artifacts:
      # תיקיית iOS המלאה
      - ios/**
      
      # תוצרי Build (debug, no signing) - מספר מיקומים אפשריים
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.dSYM
      - build/ios/iphonesimulator/*.app
      - build/ios/iphonesimulator/*.dSYM
      - build/ios/Debug-iphoneos/*.app
      - build/ios/Debug-iphonesimulator/*.app
      - build/ios/artifacts/*.app
      
      # כל תיקיית build
      - build/**
      
      # לוגים
      - flutter_drive.log
      - build.log
      
    publishing:
      email:
        recipients:
          - Idanmagor325@gmail.com
        notify:
          success: true
          failure: true

  ios-build-workflow:
    name: iOS Build - No Signing
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
    
    scripts:
      - name: Check and create iOS directory
        script: |
          echo "Checking if iOS directory exists..."
          if [ ! -d "ios" ]; then
            echo "iOS directory not found. Creating iOS platform..."
            flutter create . --platforms=ios
          else
            echo "iOS directory already exists."
          fi
          
      - name: Get Flutter dependencies
        script: |
          echo "Getting Flutter dependencies..."
          flutter packages pub get
          
      - name: Install CocoaPods dependencies
        script: |
          echo "Installing CocoaPods dependencies..."
          cd ios && pod install --repo-update
          
      - name: Flutter clean and prepare
        script: |
          echo "Cleaning Flutter project..."
          flutter clean
          flutter packages pub get
          
      - name: Build iOS without signing
        script: |
          echo "Building iOS without code signing..."
          flutter build ios --debug --no-codesign
          
      - name: List build artifacts
        script: |
          echo "Listing build artifacts..."
          find build -name "*.app" -type d
          find build -name "*.dSYM" -type d
          ls -la ios/
          
    artifacts:
      # תיקיית iOS המלאה
      - ios/**
      
      # תוצרי Build
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.dSYM
      - build/ios/iphonesimulator/*.app
      - build/ios/iphonesimulator/*.dSYM
      
      # קבצי build נוספים
      - build/ios/Debug-iphoneos/
      - build/ios/Debug-iphonesimulator/
      
      # לוגים
      - flutter_drive.log
      - build.log
      
    publishing:
      email:
        recipients:
          - Idanmagor325@gmail.com
        notify:
          success: true
          failure: true

  # Workflow מהיר לבדיקות
  ios-quick-build:
    name: iOS Quick Build - Simulator Only
    instance_type: mac_mini_m1
    max_build_duration: 30
    
    environment:
      flutter: stable
      xcode: latest
      
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.pub-cache
        
    scripts:
      - name: Check and create iOS directory
        script: |
          if [ ! -d "ios" ]; then
            flutter create . --platforms=ios
          fi
          
      - name: Get dependencies
        script: |
          flutter packages pub get
        
      - name: Build for simulator only
        script: |
          flutter build ios --debug --no-codesign --simulator
        
    artifacts:
      - ios/**
      - build/ios/iphonesimulator/*.app
      
    publishing:
      email:
        recipients:
          - Idanmagor325@gmail.com
        notify:
          success: true
          failure: true

  # Debug workflow for faster testing
  ios-debug:
    name: iOS Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    
    environment:
      flutter: stable
      xcode: latest
      
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
        
      - name: Build debug
        script: flutter build ios --debug --no-codesign --simulator
        
    artifacts:
      - build/ios/iphonesimulator/*.app
      
    publishing:
      email:
        recipients:
          - Idanmagor325@gmail.com
        notify:
          success: true
          failure: true

  # Workflow חתום לטסטים (Ad-Hoc Distribution)
  ios-adhoc-build:
    name: iOS Build - Ad-Hoc Distribution (Easier Setup)
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # הגדרות חתימה Ad-Hoc - קל יותר להגדרה מ-App Store
      # צריך רק iOS Development Certificate ו-Ad-Hoc Provisioning Profile
      ios_signing:
        distribution_type: ad_hoc  # קל יותר להגדרה מ-app_store
        bundle_identifier: com.nituvim.app
      
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
    
    scripts:
      - name: Check and create iOS directory
        script: |
          echo "Checking if iOS directory exists..."
          if [ ! -d "ios" ]; then
            echo "iOS directory not found. Creating iOS platform..."
            flutter create . --platforms=ios
          else
            echo "iOS directory already exists."
          fi
          
      - name: Get Flutter dependencies
        script: |
          echo "Getting Flutter dependencies..."
          flutter packages pub get
          
      - name: Install CocoaPods dependencies
        script: |
          echo "Installing CocoaPods dependencies..."
          cd ios && pod install --repo-update
          
      - name: Flutter clean and prepare
        script: |
          echo "Cleaning Flutter project..."
          flutter clean
          flutter packages pub get
          
      - name: Build iOS with Ad-Hoc signing
        script: |
          echo "Building iOS with Ad-Hoc code signing..."
          flutter build ios --release
          
      - name: Build IPA
        script: |
          echo "Creating IPA file..."
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-flags "-destination 'generic/platform=iOS'"
          
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/**
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.dSYM
      
    publishing:
      email:
        recipients:
          - Idanmagor325@gmail.com
        notify:
          success: true
          failure: true 