name: nituvim_ios
description: Nituvim AI - Excel Processing App for iOS (Windows Testing Version)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Excel processing
  excel: ^4.0.0
  spreadsheet_decoder: ^2.2.0
  
  # File handling (Windows compatible)
  file_picker: ^5.3.2
  path_provider: ^2.0.15
  # permission_handler: ^10.4.3  # Commented out for Windows testing
  
  # Data & Storage
  shared_preferences: ^2.2.0
  # sqflite: ^2.3.0  # Commented out - Windows uses different storage
  
  # Date & Time
  intl: ^0.18.1
  
  # Sharing & Export (Windows compatible)
  share_plus: ^7.1.0
  path: ^1.8.3
  
  # UI & Animations
  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.1.1
  # lottie: ^2.4.0  # Commented out for simplicity
  
  # State Management
  provider: ^6.0.5
  
  # Networking (if needed)
  http: ^1.1.0
  
  # Hebrew/RTL Support
  flutter_bidi: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Hebrew fonts and assets (Windows paths)
  # fonts:
  #   - family: Heebo
  #     fonts:
  #       - asset: assets/fonts/Heebo-Regular.ttf
  #       - asset: assets/fonts/Heebo-Bold.ttf
  #         weight: 700
          
  # assets:
  #   - assets/images/
  #   - assets/icons/
    
# flutter_intl:
#   enabled: true
#   arb_dir: lib/l10n
#   output_dir: lib/generated
#   output_localization_file: app_localizations.dart
#   
#   # Hebrew locale support
#   main_locale: he
#   class_name: AppLocalizations 